name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
env:
  IMAGE_NAME: idoz-demo

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
    - name: Build the Docker image
      id: build
      run: |
        TAG=$(date +%s)
        docker build . --file Dockerfile --tag $IMAGE_NAME:$TAG
        echo tag=$TAG >> $GITHUB_OUTPUT
    - name: Run Tests
      env:
        TAG: ${{ steps.build.outputs.tag }}
      run: |
        docker image ls
        docker run -d \
          --name mytest \
          -p 5000:5000 \
          $IMAGE_NAME:$TAG
        docker ps -a
        docker logs mytest >> $GITHUB_STEP_SUMMARY
    - name: Push
      env:
        TAG: ${{ steps.build.outputs.tag }}
      run: |
        docker tag $IMAGE_NAME:$TAG ido123ziv/idoz-demo:${{ github.run_number }}
        docker push ido123ziv/idoz-demo:${{ github.run_number }}


